### ISSUE TITLE
mkdir for current terraform version fails because -p flag is absent

### ISSUE THREAD

**Issue by romeshb29** [Flaconi/docker-atlantis-terragrunt#68]
https://github.com/Flaconi/docker-atlantis-terragrunt/blob/eb3111dd622d4d8cc9b708c9962d518234b685e1/Dockerfile#L29

Error screenshot
<img width="1725" alt="image" src="https://user-images.githubusercontent.com/110604723/230467621-2541d14f-a443-4063-8b0d-ddac7380a135.png">

**Comment by romeshb29** [comment]
This is happening when I am building altantis image with --target alpine. If I don't pass this arg, then final image stage is debian based in atlantis. And that fails at your Dockerfile apk command step.

**Comment by snovikov** [comment]
@romeshb29 since directory structure in base image `ghcr.io/runatlantis/atlantis` was changed - creating this repositories become obsolete. It was fixed in #69
